### ISSUE TITLE
question.

### ISSUE THREAD

**Issue by AndrewTru** [t-brieger/digital-storage#1]
hi, found the mod on the mod.factorio.com page

how does this mod work...and are any items added?

plus is it safe for adding mid-game or do you need to start fresh?

**Comment by t-brieger** [comment]
Currently, there is no content - I am actively working on it though, and the plan is for the first working prototype to be done in about 2-3 weeks.

So... sure, you *can* add it to an existing save, it just won't do much

**Comment by AndrewTru** [comment]
thanks.
